#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend chaymaaa.tech
    timeout client  30000
    bind 0:80
    default_backend chaymaaa.tech_backend

backend chaymaaa.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 440258-web-01 100.25.118.26:80 check
    server 440258-web-02 3.86.7.205:80 check
EOT

sudo service haproxy restart
